# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

status_exit = None
status_voice = None

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 481)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(68, 68, 68);\n"
                                 "background-color: rgb(39, 39, 45);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(230, 90, 16, 16))
        self.btn_edit.setStyleSheet("background-color: rgb(230, 255, 234);")
        self.btn_edit.setObjectName("btn_edit")
        self.btn_trash = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_trash.setGeometry(QtCore.QRect(250, 90, 16, 16))
        self.btn_trash.setStyleSheet("background-color: rgb(230, 255, 234);")
        self.btn_trash.setObjectName("btn_trash")
        self.main_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(10, 10, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("background-color: rgb(60,63,65);\n"
                                      "color: rgb(255, 255, 255);")
        self.main_label.setScaledContents(False)
        self.main_label.setWordWrap(False)
        self.main_label.setOpenExternalLinks(False)
        self.main_label.setObjectName("main_label")
        self.box = QtWidgets.QListView(parent=self.centralwidget)
        self.box.setGeometry(QtCore.QRect(10, 110, 261, 121))
        self.box.setObjectName("box")
        self.label_name_bot = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name_bot.setGeometry(QtCore.QRect(10, 40, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name_bot.setFont(font)
        self.label_name_bot.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name_bot.setObjectName("label_name_bot")
        self.name_bot = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_bot.setGeometry(QtCore.QRect(112, 40, 161, 21))
        self.name_bot.setStyleSheet("\n"
                                    "border-color: rgb(0, 0, 0);\n"
                                    "color: rgb(170, 255, 255);")
        self.name_bot.setObjectName("name_bot")
        self.commands = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.commands.setGeometry(QtCore.QRect(10, 110, 261, 21))
        self.commands.setStyleSheet("\n"
                                    "color: rgb(170, 255, 255);")
        self.commands.setObjectName("commands")
        self.commands_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.commands_2.setGeometry(QtCore.QRect(10, 130, 261, 21))
        self.commands_2.setStyleSheet("\n"
                                      "color: rgb(170, 255, 255);")
        self.commands_2.setObjectName("commands_2")
        self.commands_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.commands_3.setGeometry(QtCore.QRect(10, 150, 261, 21))
        self.commands_3.setStyleSheet("\n"
                                      "color: rgb(170, 255, 255);")
        self.commands_3.setObjectName("commands_3")
        self.commands_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.commands_4.setGeometry(QtCore.QRect(10, 170, 261, 21))
        self.commands_4.setStyleSheet("\n"
                                      "color: rgb(170, 255, 255);")
        self.commands_4.setObjectName("commands_4")
        self.commands_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.commands_5.setGeometry(QtCore.QRect(10, 190, 261, 21))
        self.commands_5.setStyleSheet("\n"
                                      "color: rgb(170, 255, 255);")
        self.commands_5.setObjectName("commands_5")
        self.commands_6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.commands_6.setGeometry(QtCore.QRect(10, 210, 261, 21))
        self.commands_6.setStyleSheet("\n"
                                      "color: rgb(170, 255, 255);")
        self.commands_6.setObjectName("commands_6")

        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 60, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")

        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 80, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test APP"))
        self.btn_edit.setText(_translate("MainWindow", "🖊️"))
        self.btn_trash.setText(_translate("MainWindow", "🗑\n"
                                                        ""))
        self.main_label.setText(_translate("MainWindow", "                        Настройка"))
        self.label_name_bot.setText(_translate("MainWindow", "Имя помощника: "))
        self.checkBox.setText(_translate("MainWindow", "Помощник"))
        self.checkBox_2.setText(_translate("MainWindow", "Голос Г.П."))


        # вызов проверки чек-боксов
        self.com_exit_bot()
        self.com_voice()



    # чек-бокс вкл/выкл помощника в целом
    def com_exit_bot(self):
        self.checkBox.clicked.connect(self.check_exit)

    # чек-бокс вкл/выкл озвучку помощника
    def com_voice(self):
        self.checkBox_2.clicked.connect(self.check_voice)

    # проверка чек-бокса помощника
    def check_exit(self):
        global status_exit
        if (self.checkBox.isChecked()):
            print('bot вкл')
            status_exit = True
            return status_exit
        else:
            print('bot выкл')
            status_exit = False
            return status_exit

    # проверка чек-бокса на озвучку
    def check_voice(self):
        global status_voice
        if (self.checkBox_2.isChecked()):
            print('voice вкл')
            status_voice = True
            return status_voice
        else:
            print('voice выкл')
            status_voice = False
            return status_voice




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())







# import csv
# import sys
# from PyQt5.QtWidgets import *
# from PyQt5.QtCore import Qt
# from PyQt5.QtGui import QColor
#
#
# class VoiceAssistantWindow(QMainWindow):
#     def __init__(self):
#         super().__init__()
#
#         self.setWindowTitle('Agent Smith')
#         self.setGeometry(420, 70, 600, 660)
#         self.scroll_area = QScrollArea(self)
#         self.scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
#         self.setCentralWidget(self.scroll_area)
#
#         self.table_widget = QTableWidget(self.scroll_area)
#         self.scroll_area.setWidget(self.table_widget)
#         self.load_csv_file('commands_data.csv')  # Замените 'data.csv' на путь к вашему CSV-файлу
#
#         # Устанавливаем размеры таблицы и QScrollArea
#         self.table_widget.setSizeAdjustPolicy(QTableWidget.AdjustToContents)  # Автоматическое подгонка размера таблицы
#         self.scroll_area.setWidgetResizable(True)
#         self.resize_table_cells()
#         self.colorize_table_text()
#
#     def load_csv_file(self, filename):
#         self.table_widget.clear()
#         with open(filename, 'r') as file:
#             csv_data = csv.reader(file)
#             data = list(csv_data)
#
#         self.table_widget.setRowCount(len(data))
#         self.table_widget.setColumnCount(len(data[0]))
#
#         for row_num, row_data in enumerate(data):
#             for col_num, cell_data in enumerate(row_data):
#                 item = QTableWidgetItem(cell_data)
#                 self.table_widget.setItem(row_num, col_num, item)
#
#     def resize_table_cells(self):
#         self.table_widget.resizeColumnsToContents()
#         self.table_widget.resizeRowsToContents()
#
#     def colorize_table_text(self):
#         column_count = self.table_widget.columnCount()
#         for row in range(self.table_widget.rowCount()):
#             for col in range(column_count):
#                 item = self.table_widget.item(row, col)
#                 if col == 0:
#                     # Настройка цвета текста и фона в первой колонке
#                     item.setForeground(QColor(255, 165, 0))  # Оранжевый цвет текста
#                     item.setBackground(QColor(255, 255, 255))  # Белый цвет фона
#                 elif col == 1:
#                     # Настройка цвета текста и фона во второй колонке
#                     item.setForeground(QColor(255, 0, 0))  # Красный цвет текста
#                     item.setBackground(QColor(255, 255, 255))  # Белый цвет фона
#                 elif col == 2:
#                     # Настройка цвета текста и фона в третьей колонке
#                     item.setForeground(QColor(0, 255, 255))  # Бирюзовый цвет текста
#                     item.setBackground(QColor(255, 255, 255))  # Белый цвет фона
#
#
# def application():
#     app = QApplication(sys.argv)
#     window = VoiceAssistantWindow()
#     window.show()
#     sys.exit(app.exec())
#
#
# application()
